# Site Build Settings

# jekyll-paginate configuration
paginate:            3
paginate_path:       "/blog/page:num"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Scénario — Association
title:               "Scénario"
description:         "Ateliers et jeux pour s'approprier les futurs énergétiques"
author:              "Association Scénario"
email:               "contact@scenario-asso.fr"
url:                 ""

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
